export const SET_ORIGIN = 'SET_ORIGIN';
export const SET_DESTINATION = 'SET_DESTINATION';
export const SET_TRANSPORT_MODE = 'SET_TRANSPORT_MODE';
export const FETCH_ROUTE_START = 'FETCH_ROUTE_START';
export const FETCH_ROUTE_SUCCESS = 'FETCH_ROUTE_SUCCESS';
export const FETCH_ROUTE_FAILURE = 'FETCH_ROUTE_FAILURE';
export const CLEAR_ROUTE = 'CLEAR_ROUTE';